esphome:
  name: foxess
  friendly_name: foxess

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:
  level: WARN
  baud_rate: 0

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

web_server:

external_components:
  - source:
      type: local
      path: components
    components:
      - foxess_solar

uart:
  id: uart_bus
  tx_pin: GPIO3
  rx_pin: GPIO5
  baud_rate: 9600

# button:
#   - platform: restart
#     name: "FoxESS Inverter Restart"

# text_sensor:
#   - platform: template
#     name: "FoxESS Inverter Status"
#     id: "inverter_mode_text_sensor"
#     icon: mdi:solar-power-variant

sensor:
  - platform: foxess_solar
    # phase_a:
    #   voltage:
    #     name: "FoxESS Phase A Voltage"
    #   current:
    #     name: "FoxESS Phase A Current"
    #   active_power:
    #     name: "FoxESS Phase A Power"
    #   frequency:
    #     name: "FoxESS Phase A Frequency"
    # phase_b:
    #   voltage:
    #     name: "FoxESS Phase B Voltage"
    #   current:
    #     name: "FoxESS Phase B Current"
    #   active_power:
    #     name: "FoxESS Phase B Power"
    #   frequency:
    #     name: "FoxESS Phase B Frequency"
    # phase_c:
    #   voltage:
    #     name: "FoxESS Phase C Voltage"
    #   current:
    #     name: "FoxESS Phase C Current"
    #   active_power:
    #     name: "FoxESS Phase C Power"
    #   frequency:
    #     name: "FoxESS Phase C Frequency"

    # pv1:
    #   voltage:
    #     name: "FoxESS PV1 Voltage"
    #   current:
    #     name: "FoxESS PV1 Current"
    #   active_power:
    #     name: "FoxESS PV1 Power"
    # pv2:
    #   voltage:
    #     name: "FoxESS PV2 Voltage"
    #   current:
    #     name: "FoxESS PV2 Current"
    #   active_power:
    #     name: "FoxESS PV2 Power"
    # pv3:
    #   voltage:
    #     name: "FoxESS PV3 Voltage"
    #   current:
    #     name: "FoxESS PV3 Current"
    #   active_power:
    #     name: "FoxESS PV3 Power"
    # pv4:
    #   voltage:
    #     name: "FoxESS PV4 Voltage"
    #   current:
    #     name: "FoxESS PV4 Current"
    #   active_power:
    #     name: "FoxESS PV4 Power"

    total_energy_production:
      name: "Total Energy Production"
    energy_production_day:
      name: "Today Energy Production"

    generation_power:
      name: "FoxESS Generation Power"
    # grid_power:
    #   name: "FoxESS Grid Power"
    # loads_power:
    #   name: "FoxESS Loads Power"
    # power_factor:
    #   name: "FoxESS Power Factor"
    # reactive_power:
    #   name: "FoxESS Reactive Power"

    # inverter_temp:
    #   name: "FoxESS Inverter Temp"
    # ambient_temp:
    #   name: "FoxESS Ambient Temp"
    # boost_temp:
    #   name: "FoxESS Boost Temp"

    # inverter_status:
    #   name: "FoxESS Status Code"
    #   internal: true
    #   on_value:
    #     then:
    #       - lambda: |-
    #           if (x==0) {
    #             id(inverter_mode_text_sensor).publish_state("Offline");
    #           } else if (x==1) {
    #             id(inverter_mode_text_sensor).publish_state("Online");
    #           } else if (x==2) {
    #             id(inverter_mode_text_sensor).publish_state("Error");
    #           } else {
    #             id(inverter_mode_text_sensor).publish_state("Waiting for response...");
    #           }

# Uncomment this sensor and the i2c section to use the AHT10 (remove ambient_temp above)
#  - platform: aht10
#    temperature:
#      name: "FoxESS ambient Temperature"
#    humidity:
#      name: "FoxESS ambient Humidity"

#i2c: